In [3]:
import numpy as np

In [122]:
class Neuron:
    """A class used for an intermediate or final layer neuron,
    having three input weights
    """
    def __init__(self,weights,intermediate=True):
        self.weights = weights
        if intermediate:
            self.activation_func = self._sigmoid
        else:
            self.activation_func = self._sigmoid
    
    def predict(self, X):
        """Gives a prediction for a given value of X
        """
        prediction_pre = np.dot(X, self.weights)
        prediction = self.activation_func(prediction_pre)
        return prediction
    
    def _sigmoid(self, x):
        """Sigmoid activation function
        """
        
        return 1/(1+np.exp(-x))

    def _none(self,x):
        return x
    
    def _relu(self, x):
        """ReLU activation function:
        """
        
        return np.where(x>=0,x,0)

In [166]:
def xor_net(inputs, weights):
    """Simulates an XOR network
    """
    node1 = Neuron(weights[0:3])
    node2 = Neuron(weights[3:6])
    node3 = Neuron(weights[6:9],False)
    
    bias0 = bias1 = bias2 = 1
    
    in1 = np.array([bias0,inputs[0],inputs[1]])
    in2 = np.array([bias1,inputs[0],inputs[1]])
          
    out1 = node1.predict(in1)
    out2 = node2.predict(in2)
    
    out_final = node3.predict(np.array([bias2, out1, out2]))
    
    return out_final

def mse(weights):
    """Creates an XOR network with given weights for all four input vectors
    ans computes the mean square error for all of them"""
    pred00 = xor_net([0,0],weights)
    pred01 = xor_net([0,1],weights)
    pred10 = xor_net([1,0],weights)
    pred11 = xor_net([1,1],weights)
    print(pred00,pred01,pred10,pred11)
    
    error = np.array([pred00-0,pred01-1,pred10-1,pred11-0])
    print(error)
    
    mse = np.mean(error**2)
    
    return mse

def one_one(index, change):
    cx = np.zeros(9)
    cx[index] = 1
    return change*cx

def mse_diff(weights1, weights2):
    mse1 = mse(weights1)
    mse2 = mse(weights2)
    return mse2-mse1
    

def grdmse(weights):
    """Returns a vector of partial derivatives of dMSE/DW, i.e.;
    the amount of change in the MSE as a result of a small change 
    in each weight.
    """
    change = 0.1
    cvs = []
    for i in range(len(weights)):
        ci = one_one(i, change)
        cvs.append(ci)
        

    gradient = np.array([mse_diff(weights,weights+cvs[0]),mse_diff(weights,weights+cvs[1]),mse_diff(weights,weights+cvs[2]),
                        mse_diff(weights,weights+cvs[3]),mse_diff(weights,weights+cvs[4]),mse_diff(weights,weights+cvs[5]),
                        mse_diff(weights,weights+cvs[6]),mse_diff(weights,weights+cvs[7]),mse_diff(weights,weights+cvs[8])])
    
    return gradient

In [175]:
w = [0.1,1,0,1,1,0,1,0.1,0.1]
grdmse(w)

0.7550266794254394 0.7550266794254394 0.7618965819535792 0.7618965819535792
[ 0.75502668 -0.24497332 -0.23810342  0.76189658]
0.75548610599939 0.75548610599939 0.7622277632936291 0.7622277632936291
[ 0.75548611 -0.24451389 -0.23777224  0.76222776]
0.7550266794254394 0.7550266794254394 0.7618965819535792 0.7618965819535792
[ 0.75502668 -0.24497332 -0.23810342  0.76189658]
0.7550266794254394 0.7550266794254394 0.7622277632936291 0.7622277632936291
[ 0.75502668 -0.24497332 -0.23777224  0.76222776]
0.7550266794254394 0.7550266794254394 0.7618965819535792 0.7618965819535792
[ 0.75502668 -0.24497332 -0.23810342  0.76189658]
0.7550266794254394 0.75548610599939 0.7618965819535792 0.7622277632936291
[ 0.75502668 -0.24451389 -0.23810342  0.76222776]
0.7550266794254394 0.7550266794254394 0.7618965819535792 0.7618965819535792
[ 0.75502668 -0.24497332 -0.23810342  0.76189658]
0.7553816596031694 0.7553816596031694 0.762079868383952 0.762079868383952
[ 0.75538166 -0.24461834 -0.23792013  0.76207987]


array([2.04061671e-04, 8.67901015e-05, 6.99695273e-05, 1.38611308e-04,
       4.80188866e-05, 2.63822172e-05, 9.54042216e-03, 6.07219318e-03,
       7.68144329e-03])

In [39]:
a = [0,1]
b = 1
print(np.squeeze([a,b]))

[list([0, 1]) 1]


C:\Users\elvis\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)
