In [1]:
import numpy as np
import pandas as pd

In [2]:
train_in = pd.read_csv("train_in.csv")
train_out = pd.read_csv("train_out.csv")
test_in = pd.read_csv("test_in.csv")
test_out = pd.read_csv("test_out.csv")

In [3]:
train_in = np.array(train_in)
train_out = np.array(train_out)
test_in = np.array(test_in)
test_out = np.array(test_out)

In [4]:
train_out = np.squeeze(train_out, axis=1)
test_out = np.squeeze(test_out, axis=1)

In [5]:
d_x = np.arange(0,1706,1)
d_y = np.arange(0,10,1)
digit_x, digit_y = np.meshgrid(d_x, d_y)
print(digit_y)

[[0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [2 2 2 ... 2 2 2]
 ...
 [7 7 7 ... 7 7 7]
 [8 8 8 ... 8 8 8]
 [9 9 9 ... 9 9 9]]


In [23]:
class Perceptron:
    
    def __init__(self, digit=digit_y, weight=np.random.uniform(size=(256, 10)), bias=np.random.uniform(size=(10)), learning_rate=0.01, n_iters=100):
        self.lr = learning_rate
        self.n_iter = n_iters
        self.activation = self._val_func
        
        self.weights = weight
        self.bias = bias
        self.digit = digit
        
    def fit(self, x, y):
        
        y_m = np.repeat([y], [10], axis=0)
        y_ = np.ones(shape=y_m.shape)*(y_m==self.digit)
        
        for _ in range(self.n_iter):
            for i, x_i in enumerate(x):
                prediction = self.predict(x_i)
                update = self.lr*(y_[:,i]-self._u_step(prediction))

                self.weights += update * np.transpose(np.repeat(x_i[None,...], [10], axis=0))
                self.bias += update
                
    def predict(self, x):
        linear_output = np.dot(x, self.weights)+self.bias
        y_predicted = self.activation(linear_output)
        return linear_output
    
    
    def _val_func(self, x):
        return np.where(x>=0,x,0)
    
    def _u_step(self, x):
        
        return np.where(x>0,1,0)

In [24]:
p = Perceptron()
p.fit(train_in, train_out)
predictions = p.predict(test_in)
print(np.shape(predictions))
print(predictions)

predictions = np.argmax(np.squeeze(predictions), axis=1)
print(predictions)

diff = predictions-test_out
success_rate = len(np.where(diff==0)[0])/len(test_out)
print(success_rate)

(999, 10)
[[ 20.15317051 -19.12543239  -8.02285727 ... -17.73755444  -3.46962854
  -14.86028197]
 [  6.49536853 -22.44211984  -9.32420105 ... -15.35883967  -5.19760883
   -5.3425802 ]
 [ 13.57407331 -29.10430927 -10.12913747 ... -13.52622771  -4.30146653
  -20.03310167]
 ...
 [-12.91003941 -25.65268463  -6.0833196  ... -16.9747651    2.31727575
   -8.17996223]
 [-22.25410273 -16.76479354  -3.65983067 ...   0.7480921   -8.9218745
   -2.30850967]
 [ 15.06963619 -24.3221397  -11.75749719 ... -17.69671916 -10.67962016
  -18.9148352 ]]
